### PR TITLE
Fixed bug when only last of multiple titles was rendered

### PR DESCRIPTION
**Pull request by adrag239**

### CODE REVIEW

**Comment by eraydin** [comment]
Thank you @adrag239

**Comment by adrag239** [comment]
Thanks! Any plans when it will be included into next release as we rely on this functionality?

**Comment by eraydin** [comment]
Hello @adrag239,

Yes, it will be included into the next release, but I found yet another bug related with this issue. Have you tried to save the generated Excel package into a file, and re-read it again? It does not read. It throws a validation exception. After fixing this problem, I will release a new version including your changes.

Thank you again,
Have a good eve.

**Comment by adrag239** [comment]
In our scenario we just generate Excel files and open them in Excel, so we have not faced problem with parsing. But now I understand the issue.

Thanks!

**Comment by eraydin** [comment]
Released https://www.nuget.org/packages/EPPlus.Core.Extensions/2.3.2

**Pull request merged**
